# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Install
          uses: ianwalter/puppeteer@afefc4bee7341a77baa94503da684e2895ea5d30
          with:
           args: npm install @wdio/cli
        - name: Test
          uses: ianwalter/puppeteer@afefc4bee7341a77baa94503da684e2895ea5d30
          with:
           args: npx wdio run ./wdio.conf.js
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs
